-- TALLER 5 oracle
ALTER USER "TALLER5ORACLE"  QUOTA UNLIMITED ON USERS;
CREATE TABLE clientes ( 
    nombre VARCHAR2(60) NOT NULL,
    identificacion VARCHAR2(10) PRIMARY KEY,
    edad NUMBER NOT NULL,
    correo VARCHAR2(64)
);

CREATE TABLE productos(
    codigo VARCHAR2(8) PRIMARY KEY,
    nombre VARCHAR2(60) NOT NULL,
    stock NUMBER NOT NULL,
    valor_unitario NUMBER NOT NULL
);

CREATE TABLE facturas(
    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, 
    fecha DATE NOT NULL,
    cantidad NUMBER NOT NULL,
    valor_total NUMBER NOT NULL,
    pedido_estado VARCHAR2(10) CHECK (pedido_estado IN ('PENDIENTE', 'BLOQUEADO', 'ENTREGADO')),
    producto_id VARCHAR2(8),
    cliente_id VARCHAR2(10),
    FOREIGN KEY (producto_id) REFERENCES productos(codigo),
    FOREIGN KEY (cliente_id) REFERENCES clientes(identificacion)
);

CREATE TABLE auditoria(
    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    fecha_inicio DATE NOT NULL,
    fecha_final DATE NOT NULL,
    factura_id NUMBER,
    pedido_estado VARCHAR2(10) CHECK (pedido_estado IN ('PENDIENTE', 'BLOQUEADO', 'ENTREGADO')),
    FOREIGN KEY (factura_id) REFERENCES facturas(id)
);

BEGIN
    INSERT INTO clientes (identificacion, nombre, edad, correo) VALUES ('1022322054', 'miguel angel', 20, 'miguelonperez300@gmail.com');
    INSERT INTO clientes (identificacion, nombre, edad, correo) VALUES ('1022322055', 'santiago valencia', 18, 'miguelonperez300@gmail.com');
    INSERT INTO clientes (identificacion, nombre, edad, correo) VALUES ('1022322056', 'manuel alejandro', 19, 'miguelonperez300@gmail.com');

    INSERT INTO productos(codigo, nombre, stock, valor_unitario) VALUES ('1', 'pollo', 50, 15000);
    INSERT INTO productos(codigo, nombre, stock, valor_unitario) VALUES ('2', 'carne', 50, 20000);
    INSERT INTO productos(codigo, nombre, stock, valor_unitario) VALUES ('3', 'huevo', 50, 600);

    INSERT INTO facturas(fecha, cantidad, valor_total, pedido_estado, producto_id, cliente_id) VALUES (TO_DATE('2003-11-12', 'YYYY-MM-DD'), 2, 30000, 'ENTREGADO', '1', '1022322054');
    INSERT INTO facturas(fecha, cantidad, valor_total, pedido_estado, producto_id, cliente_id) VALUES (TO_DATE('2003-11-13', 'YYYY-MM-DD'), 4, 80000, 'PENDIENTE', '2', '1022322055');
    INSERT INTO facturas(fecha, cantidad, valor_total, pedido_estado, producto_id, cliente_id) VALUES (TO_DATE('2003-11-14', 'YYYY-MM-DD'), 2, 1200, 'BLOQUEADO', '3', '1022322056');
END;

-- PARTE 1
CREATE OR REPLACE PROCEDURE obtener_total_stock IS
    v_total_stock NUMBER := 0;
    v_stock_actual NUMBER;
    v_nombre_producto VARCHAR2(60);
BEGIN
    FOR rec IN (SELECT nombre, stock FROM productos) LOOP
        v_nombre_producto := rec.nombre;
        v_stock_actual := rec.stock;
        DBMS_OUTPUT.PUT_LINE('El nombre del producto es: ' || v_nombre_producto);
        DBMS_OUTPUT.PUT_LINE('El stock actual del producto es de: ' || v_stock_actual);
        v_total_stock := v_total_stock + v_stock_actual;
    END LOOP;
    DBMS_OUTPUT.PUT_LINE('El stock total es de: ' || v_total_stock);
END obtener_total_stock;

BEGIN
    obtener_total_stock;
END;

-- PARTE 2
CREATE OR REPLACE PROCEDURE generar_auditoria(
    P_fecha_inicio IN DATE,
    p_fecha_final IN DATE
) IS
    v_id_factura NUMBER;
    v_estado_factura VARCHAR2(10);
    v_fecha DATE;
BEGIN
    FOR rec IN (SELECT fecha, id, pedido_estado FROM facturas) LOOP
        v_fecha := rec.fecha;
        v_id_factura := rec.id;
        v_estado_factura := rec.pedido_estado;
        IF v_fecha BETWEEN P_fecha_inicio AND p_fecha_final THEN
            INSERT INTO auditoria(fecha_inicio, fecha_final, factura_id, pedido_estado)
            VALUES (P_fecha_inicio, p_fecha_final, v_id_factura, v_estado_factura);
            DBMS_OUTPUT.PUT_LINE('Se ha creado la auditoria');
        END IF;
    END LOOP;
END generar_auditoria;

BEGIN
    generar_auditoria(TO_DATE('2000-11-12', 'YYYY-MM-DD'), TO_DATE('2004-11-12', 'YYYY-MM-DD'));
END;


-- PARTE 3
CREATE OR REPLACE PROCEDURE simular_ventas_mes IS
    v_dia NUMBER := 1;
    v_identificacion VARCHAR2(10);
    v_cantidad_random NUMBER;
BEGIN
    WHILE v_dia <= 30 LOOP
        FOR rec IN (SELECT identificacion FROM clientes) LOOP
            v_identificacion := rec.identificacion;
            v_cantidad_random := FLOOR(1 + DBMS_RANDOM.VALUE * 2);
            INSERT INTO facturas(fecha, cantidad, valor_total, pedido_estado, producto_id, cliente_id)
            VALUES (TO_DATE('2024-09-02', 'YYYY-MM-DD'), v_cantidad_random, 30000, 'ENTREGADO', '1', v_identificacion);
            DBMS_OUTPUT.PUT_LINE('Se creó una factura');
        END LOOP;
        v_dia := v_dia + 1;
    END LOOP;
END simular_ventas_mes;

BEGIN
    simular_ventas_mes;
END;
